### ISSUE TITLE
Cannot find module 'lil-http' from '/home/rafa/projects/front/node_modules/resilient/lib'

### ISSUE THREAD

**Issue by rafinskipg** [resilient-http/resilient.js#113]
Hi 

I guess it's a minor bug

```
Running "browserify:library" (browserify) task
>> Error: Cannot find module 'lil-http' from '/home/rafa/projects/front/node_modules/resilient/lib'
```

**Comment by h2non** [comment]
Thanks for reporting

`lil-http` was a development dependency only, since it's used only for the embed the module exclusively in the generated browser bundle. 
At `node/io` runtime level this module is not required, and therefore it's not needed to provision it via `npm`

The issue is related about how `browserify` discovers your package dependencies parsing your code via Esprima and walking recursively through the AST in order to infer all the `require()` calls.

I'll accept the PR to make more easy to generate `browserified` bundles which embed `resilient` since I think could be useful for some specific use cases, but in general you should simply depend on it as third-party library without embedding it in your project specific code

**Comment by h2non** [comment]
A new fresh `0.2.27` version which fixes this issue is now available from npm/bower.

```bash
npm update resilient
```

**Comment by rafinskipg** [comment]
Hi @h2non 

I use browserify for creating the bundle with all the third party dependencies (if they are available from NPM ) so it can be great if `resilient` worked that way. 

PD: while comenting i saw your update, thanks for the new version, updating.

**Comment by h2non** [comment]
Great!

Btw, if you are using Angular, you may take a look at this wrapped I've created for a better framework specific approach:
https://github.com/h2non/angular-resilient

Otherwise feel free to create a specific wrapper of `Resilient` for the framework you're using. 
Anyway I'd like to listen some opinions about `Resilient` use cases in other frameworks and app scenarios
